#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

[ -f ~/.config/zsh/.zshenv ] && . ~/.config/zsh/.zshenv
#xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

#poor mans autostart
#autostart="mpd xcompmgr dunst unclutter pipewire"
#
#for program in $autostart; do
#	pidof -s "$program" || "$program" &
#done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
